---
title: The Most Visited National Parks of 2020
author: Sangeeta Shah
date: November 3, 2021
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, cache=T)
```  

&nbsp;  

The map below shows top 10 most visited national parks and recreational areas in 2020.  
The circle radii indicate the number of visitors.  

```{r message=F, warning=F, error=F}
library(leaflet); library(htmltools); library(ggmap)
parks <- c(
    'Blue Ridge PKWY',
    'Golden Gate NRA',
    'Great Smoky Mountains NP',
    'Gateway NRA',
    'Lake Mead NRA',
    'George Washington MEM PKWY',
    'Natchez Trace PKWY',
    'Chesapeake & Ohio Canal NHP',
    'Cape Cod NS',
    'Delaware Water Gap NRA')
Rank <- 1:10
visits <- c(14099485, 12400045, 12095720, 8404728, 8016510,
            6237361, 6124808, 4888436, 4083505, 4068529)
websites <- c(
    'https://www.blueridgeparkway.org/',
    'https://www.nps.gov/goga/index.htm',
    'https://www.nps.gov/grsm/index.htm',
    'https://www.nps.gov/gate/index.htm',
    'https://www.nps.gov/lake/index.htm',
    'https://www.nps.gov/gwmp/index.htm',
    'https://www.nps.gov/natr/index.htm',
    'https://www.nps.gov/choh/index.htm',
    'https://www.nps.gov/caco/index.htm',
    'https://www.nps.gov/dewa/index.htm')
NPSIcon <- makeIcon(
   iconUrl = 'tree.png',
   iconWidth = 20, iconHeight = 20, iconAnchorX = 10, iconAnchorY = 10)
locations <- data.frame(
    lat = c(35.7647, 37.8480, 35.6131, 40.4397, 36.1551,
            38.9618, 34.3302, 39.0007, 41.9043, 41.1044),
    lng = c(-82.2653, -122.5295, -83.5532, -73.9887, -114.4559,
            -77.1463, -88.7098, -77.2502, -69.9789, -74.9443)
)

labels <- paste0(parks, '<br>', paste('visits in 2020:', round(visits/1000000, 2), 'millions'))
websites <- paste0('<a href="', websites, '">', parks, '</a>')

locations %>% leaflet() %>% addTiles() %>%
    addMarkers(icon=NPSIcon, label= lapply(labels, htmltools::HTML), popup=lapply(websites, htmltools::HTML)) %>%
    addCircleMarkers(weight=1, radius= ~visits/300000, color='white', opacity=30) %>% 
    addProviderTiles('Esri.WorldImagery')
```

<script>
marker.bindPopup("Popup content");
        marker.on('mouseover', function (e) {
            this.openPopup();
        });
        marker.on('mouseout', function (e) {
            this.closePopup();
        });
</script>
    
<span style='font-size: 10px;'>** Data source: [National Park Service][1]</span>  

[1]: https://irma.nps.gov/STATS/Reports/National
